version: "3.2"
services:
  server:
    image: ypapax/https_listen
    command: bash /usr/share/nginx/html/entrypoint.sh
    container_name: https_gclb_compose
    ports:
      - 80:80/tcp
      - 8080:8080/tcp